### ISSUE TITLE
malloc/free in non windows platform

### ISSUE THREAD

**Issue by mattiascibien** [flibitijibibo/Vorbisfile-CS#1]
Hello,

I have been looking in the source code for this library to replace NVorbis in my project. What I am looking into is on how the *malloc/free* implementation is handled in other platforms as I can see it is imported from `msvcrt.dll` in https://github.com/flibitijibibo/Vorbisfile-CS/blob/master/Vorbisfile.cs#L42-L52.

**Comment by flibitijibibo** [comment]
The Mono runtime's configuration will have a mapping for msvcrt that maps to libc on other targets. It will look like this:

https://github.com/flibitijibibo/MonoKickstart/blob/master/precompiled/monoconfig#L21
